import Head from 'next/head'
import Navbar from '../components/Navbar'
import Main from '../components/Main'
import About from '../components/About'
import Experience from '../components/Experience'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Jia Wei | Front-End Developer</title>
        <meta name="description" content="Generated by create nextapp"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Navbar/>
      <Main/>
      <About/>
      <Experience/>
    </div>
  )
}
