import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Jia Wei | Front-End Developer</title>
        <meta name="description" content="Generated by create nextapp"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Navbar/>
    </div>
  )
}
